export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_ERR = 'FETCH_AUTHORS_ERR';
export const ADD_AUTHOR = 'ADD_AUTHOR';
export const ADD_AUTHOR_SUCCESS = 'ADD_AUTHOR_SUCCESS';
export const ADD_AUTHOR_ERR = 'ADD_AUTHOR_ERR';
