export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSES_ERR = 'FETCH_COURSES_ERR';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';

export const ADD_COURSE = 'ADD_COURSE';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_ERR = 'ADD_COURSE_ERR';

export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_ERR = 'DELETE_COURSE_ERR';

export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_ERR = 'UPDATE_COURSE_ERR';

export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_ERR = 'GET_COURSE_ERR';

export const SEARCH_COURSE = 'SEARCH_COURSE';
export const SEARCH_COURSE_SUCCESS = 'SEARCH_COURSE_SUCCESS';
export const SEARCH_COURSE_ERR = 'SEARCH_COURSE_ERR';
